name: project1
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - lib/assets/fantasma.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: LibreBaskerville
      fonts:
        - asset: lib/assets/fonts/LibreBaskerville-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/LibreBaskerville-Italic.ttf
          weight: 400
        - asset: lib/assets/fonts/LibreBaskerville-Regular.ttf
          weight: 400

  uses-material-design: true
